// Generated by gencpp from file cam_monitor/SnapResponse.msg
// DO NOT EDIT!


#ifndef CAM_MONITOR_MESSAGE_SNAPRESPONSE_H
#define CAM_MONITOR_MESSAGE_SNAPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cam_monitor
{
template <class ContainerAllocator>
struct SnapResponse_
{
  typedef SnapResponse_<ContainerAllocator> Type;

  SnapResponse_()
    : done(false)  {
    }
  SnapResponse_(const ContainerAllocator& _alloc)
    : done(false)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::cam_monitor::SnapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cam_monitor::SnapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SnapResponse_

typedef ::cam_monitor::SnapResponse_<std::allocator<void> > SnapResponse;

typedef boost::shared_ptr< ::cam_monitor::SnapResponse > SnapResponsePtr;
typedef boost::shared_ptr< ::cam_monitor::SnapResponse const> SnapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cam_monitor::SnapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cam_monitor::SnapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cam_monitor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cam_monitor::SnapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cam_monitor::SnapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cam_monitor::SnapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cam_monitor::SnapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cam_monitor::SnapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cam_monitor::SnapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cam_monitor::SnapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::cam_monitor::SnapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89bb254424e4cffeULL;
  static const uint64_t static_value2 = 0xdbf494e7b0ddbfeaULL;
};

template<class ContainerAllocator>
struct DataType< ::cam_monitor::SnapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cam_monitor/SnapResponse";
  }

  static const char* value(const ::cam_monitor::SnapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cam_monitor::SnapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool done\n\
";
  }

  static const char* value(const ::cam_monitor::SnapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cam_monitor::SnapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SnapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cam_monitor::SnapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cam_monitor::SnapResponse_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAM_MONITOR_MESSAGE_SNAPRESPONSE_H
