uint32 time_recorded

int16 bme01_temp
int16 bme01_pres
uint8 bme01_humi

int16 bme02_temp
int16 bme02_pres
uint8 bme02_humi

int16 dallas01_temp
int16 dallas02_temp
int16 dallas03_temp
int16 dallas04_temp
int16 dallas05_temp
int16 dallas06_temp
int16 dallas07_temp
int16 dallas08_temp
int16 dallas09_temp
int16 dallas10_temp
int16 dallas11_temp
int16 dallas12_temp
int16 dallas13_temp
int16 dallas14_temp
int16 dallas15_temp
int16 dallas16_temp