uint32 time_recorded

int8 turntable_temp
uint8 turntable_velo
int16 turntable_goal
int16 turntable_posi
bool turntable_onoff

int8 shoulder_temp
uint8 shoulder_velo
int16 shoulder_goal
int16 shoulder_posi
bool shoulder_onoff

int8 elbow_temp
uint8 elbow_velo
int16 elbow_goal
int16 elbow_posi
bool elbow_onoff

int8 wrist_temp
uint8 wrist_velo
int16 wrist_goal
int16 wrist_posi
bool wrist_onoff

int8 gripper_temp
uint8 gripper_velo
int16 gripper_goal
int16 gripper_posi
bool gripper_onoff

int16 armposition_in_mm_X
int16 armposition_in_mm_Y
int16 armposition_in_mm_Z
int16 armorientation_in_rads