#goal definition
sensor_msgs/JointState[] rotation
sensor_msgs/JointState[] shoulder
sensor_msgs/JointState[] elbow
sensor_msgs/JointState[] wrist
---
#result definition
bool success
---
#feedback definition
sensor_msgs/JointState rotation
sensor_msgs/JointState shoulder
sensor_msgs/JointState elbow
sensor_msgs/JointState wrist
