// Generated by gencpp from file ram_network/HaspCommand.msg
// DO NOT EDIT!


#ifndef RAM_NETWORK_MESSAGE_HASPCOMMAND_H
#define RAM_NETWORK_MESSAGE_HASPCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ram_network
{
template <class ContainerAllocator>
struct HaspCommand_
{
  typedef HaspCommand_<ContainerAllocator> Type;

  HaspCommand_()
    : com_id(0)
    , com_param(0)  {
    }
  HaspCommand_(const ContainerAllocator& _alloc)
    : com_id(0)
    , com_param(0)  {
  (void)_alloc;
    }



   typedef uint8_t _com_id_type;
  _com_id_type com_id;

   typedef uint8_t _com_param_type;
  _com_param_type com_param;





  typedef boost::shared_ptr< ::ram_network::HaspCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ram_network::HaspCommand_<ContainerAllocator> const> ConstPtr;

}; // struct HaspCommand_

typedef ::ram_network::HaspCommand_<std::allocator<void> > HaspCommand;

typedef boost::shared_ptr< ::ram_network::HaspCommand > HaspCommandPtr;
typedef boost::shared_ptr< ::ram_network::HaspCommand const> HaspCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ram_network::HaspCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ram_network::HaspCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ram_network

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ram_network': ['/home/korisd/tUR/ROSCode/RAM/src/ram_network/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ram_network::HaspCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ram_network::HaspCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ram_network::HaspCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ram_network::HaspCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ram_network::HaspCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ram_network::HaspCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ram_network::HaspCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1053530576d45dc789fcb9bb7fd75de";
  }

  static const char* value(const ::ram_network::HaspCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1053530576d45dcULL;
  static const uint64_t static_value2 = 0x789fcb9bb7fd75deULL;
};

template<class ContainerAllocator>
struct DataType< ::ram_network::HaspCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ram_network/HaspCommand";
  }

  static const char* value(const ::ram_network::HaspCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ram_network::HaspCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 com_id\n\
uint8 com_param\n\
";
  }

  static const char* value(const ::ram_network::HaspCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ram_network::HaspCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.com_id);
      stream.next(m.com_param);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HaspCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ram_network::HaspCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ram_network::HaspCommand_<ContainerAllocator>& v)
  {
    s << indent << "com_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.com_id);
    s << indent << "com_param: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.com_param);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAM_NETWORK_MESSAGE_HASPCOMMAND_H
